// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ShopCoApi.Data;

#nullable disable

namespace ShopCoApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251105072626_InitialSchemaForPostgres")]
    partial class InitialSchemaForPostgres
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("ShopCoApi.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("ShopCoApi.Models.CartItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ProductVariantId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int>("ShoppingCartId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProductVariantId");

                    b.HasIndex("ShoppingCartId");

                    b.ToTable("CartItems");
                });

            modelBuilder.Entity("ShopCoApi.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ParentCategoryId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParentCategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Men"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Women"
                        },
                        new
                        {
                            Id = 3,
                            Name = "T-Shirts",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 4,
                            Name = "Shirts",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Jeans",
                            ParentCategoryId = 1
                        },
                        new
                        {
                            Id = 6,
                            Name = "Dresses",
                            ParentCategoryId = 2
                        });
                });

            modelBuilder.Entity("ShopCoApi.Models.Color", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HexCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Colors");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HexCode = "#000000",
                            Name = "Black"
                        },
                        new
                        {
                            Id = 2,
                            HexCode = "#FFFFFF",
                            Name = "White"
                        },
                        new
                        {
                            Id = 3,
                            HexCode = "#4F4631",
                            Name = "Olive"
                        },
                        new
                        {
                            Id = 4,
                            HexCode = "#31344F",
                            Name = "Navy"
                        },
                        new
                        {
                            Id = 5,
                            HexCode = "#FF0000",
                            Name = "Red"
                        },
                        new
                        {
                            Id = 6,
                            HexCode = "#0000FF",
                            Name = "Blue"
                        });
                });

            modelBuilder.Entity("ShopCoApi.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("AverageRating")
                        .HasColumnType("double precision");

                    b.Property<decimal>("BasePrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DetailedDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AverageRating = 4.5,
                            BasePrice = 30.00m,
                            CategoryId = 3,
                            Description = "This graphic t-shirt which is perfect for any occasion. Crafted from a soft and breathable fabric, it offers superior comfort and style.",
                            DetailedDescription = "Made from 100% premium ring-spun cotton, this t-shirt features a unique graphic print designed by our in-house artists. The fabric is pre-shrunk to maintain its shape after washing, and the fit is a modern, slightly tapered cut.",
                            Name = "ONE LIFE GRAPHIC T-SHIRT"
                        },
                        new
                        {
                            Id = 2,
                            AverageRating = 4.2000000000000002,
                            BasePrice = 75.00m,
                            CategoryId = 5,
                            Description = "A modern take on a classic, these skinny fit jeans offer a sleek silhouette and all-day comfort. Made with stretch denim for a perfect fit.",
                            DetailedDescription = "Our skinny fit jeans are crafted from a high-quality denim blend (98% cotton, 2% elastane) for the perfect combination of structure and stretch. Features a classic five-pocket design, zip fly, and a branded leather patch on the back.",
                            Name = "Skinny Fit Jeans"
                        },
                        new
                        {
                            Id = 3,
                            AverageRating = 4.7999999999999998,
                            BasePrice = 55.00m,
                            CategoryId = 4,
                            Description = "A timeless checkered shirt that adds a touch of rustic charm to your wardrobe. Made from 100% premium cotton.",
                            DetailedDescription = "This versatile shirt is perfect for layering or wearing on its own. It features a button-down collar, a single chest pocket, and adjustable cuffs. The flannel fabric is soft to the touch and provides warmth on cooler days.",
                            Name = "Classic Checkered Shirt"
                        });
                });

            modelBuilder.Entity("ShopCoApi.Models.ProductFaq", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductFaqs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "We offer a 30-day return policy for all unworn items.",
                            ProductId = 1,
                            Question = "What is the return policy?"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "This t-shirt is made from 100% premium ring-spun cotton.",
                            ProductId = 1,
                            Question = "What material is this t-shirt made of?"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "We recommend washing inside out in cold water and hanging to dry to preserve the color and fit.",
                            ProductId = 2,
                            Question = "How do I wash these jeans?"
                        });
                });

            modelBuilder.Entity("ShopCoApi.Models.ProductImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("ProductImages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            IsPrimary = true,
                            ProductId = 1,
                            Url = "https://cdn.pixabay.com/photo/2024/04/29/04/21/tshirt-8726716_1280.jpg"
                        },
                        new
                        {
                            Id = 2,
                            IsPrimary = false,
                            ProductId = 1,
                            Url = "https://tse3.mm.bing.net/th/id/OIP.XbpNO0eM9CaAjnmV16uibwHaHa?pid=ImgDet&w=203&h=203&c=7&o=7&rm=3"
                        },
                        new
                        {
                            Id = 3,
                            IsPrimary = false,
                            ProductId = 1,
                            Url = "https://tse1.mm.bing.net/th/id/OIP.AT3AZiJg2Z04rkIJV0OZWAHaHa?pid=ImgDet&w=203&h=203&c=7&o=7&rm=3"
                        },
                        new
                        {
                            Id = 4,
                            IsPrimary = true,
                            ProductId = 2,
                            Url = "https://th.bing.com/th/id/OIF.pWER61jZ9Co6Xr1SZGIfYg?w=203&h=254&c=7&r=0&o=7&pid=1.7&rm=3"
                        },
                        new
                        {
                            Id = 5,
                            IsPrimary = true,
                            ProductId = 3,
                            Url = "https://th.bing.com/th/id/OIP.e__xPKL6FeicKbfiRqli1AHaJ4?w=148&h=198&c=7&r=0&o=7&pid=1.7&rm=3"
                        });
                });

            modelBuilder.Entity("ShopCoApi.Models.ProductVariant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ColorId")
                        .HasColumnType("integer");

                    b.Property<decimal?>("OriginalPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<int>("SizeId")
                        .HasColumnType("integer");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ColorId");

                    b.HasIndex("ProductId");

                    b.HasIndex("SizeId");

                    b.ToTable("ProductVariants");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ColorId = 3,
                            OriginalPrice = 30.00m,
                            Price = 25.00m,
                            ProductId = 1,
                            SizeId = 2,
                            StockQuantity = 20
                        },
                        new
                        {
                            Id = 2,
                            ColorId = 3,
                            OriginalPrice = 30.00m,
                            Price = 30.00m,
                            ProductId = 1,
                            SizeId = 3,
                            StockQuantity = 15
                        },
                        new
                        {
                            Id = 3,
                            ColorId = 4,
                            Price = 30.00m,
                            ProductId = 1,
                            SizeId = 2,
                            StockQuantity = 25
                        },
                        new
                        {
                            Id = 4,
                            ColorId = 4,
                            Price = 30.00m,
                            ProductId = 1,
                            SizeId = 3,
                            StockQuantity = 10
                        },
                        new
                        {
                            Id = 5,
                            ColorId = 6,
                            OriginalPrice = 65.00m,
                            Price = 75.00m,
                            ProductId = 2,
                            SizeId = 1,
                            StockQuantity = 12
                        },
                        new
                        {
                            Id = 6,
                            ColorId = 6,
                            Price = 75.00m,
                            ProductId = 2,
                            SizeId = 2,
                            StockQuantity = 30
                        },
                        new
                        {
                            Id = 7,
                            ColorId = 6,
                            Price = 75.00m,
                            ProductId = 2,
                            SizeId = 3,
                            StockQuantity = 18
                        },
                        new
                        {
                            Id = 8,
                            ColorId = 5,
                            Price = 55.00m,
                            ProductId = 3,
                            SizeId = 3,
                            StockQuantity = 22
                        });
                });

            modelBuilder.Entity("ShopCoApi.Models.Review", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("PostedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProductId")
                        .HasColumnType("integer");

                    b.Property<double>("Rating")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.ToTable("Reviews");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AuthorName = "Samantha D.",
                            Comment = "I absolutely love this t-shirt! The design is unique and the fabric feels so comfortable.",
                            PostedDate = new DateTime(2023, 8, 14, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Rating = 4.5
                        },
                        new
                        {
                            Id = 2,
                            AuthorName = "Alex M.",
                            Comment = "The quality is top-notch. It's become my favorite go-to shirt.",
                            PostedDate = new DateTime(2023, 8, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 1,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 3,
                            AuthorName = "Ethan R.",
                            Comment = "These jeans fit perfectly. The stretch material is very comfortable for all-day wear.",
                            PostedDate = new DateTime(2023, 8, 16, 0, 0, 0, 0, DateTimeKind.Utc),
                            ProductId = 2,
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("ShopCoApi.Models.ShoppingCart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("ShoppingCarts");
                });

            modelBuilder.Entity("ShopCoApi.Models.Size", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Small"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Large"
                        },
                        new
                        {
                            Id = 4,
                            Name = "X-Large"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("ShopCoApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("ShopCoApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopCoApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("ShopCoApi.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopCoApi.Models.CartItem", b =>
                {
                    b.HasOne("ShopCoApi.Models.ProductVariant", "ProductVariant")
                        .WithMany()
                        .HasForeignKey("ProductVariantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopCoApi.Models.ShoppingCart", null)
                        .WithMany("Items")
                        .HasForeignKey("ShoppingCartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductVariant");
                });

            modelBuilder.Entity("ShopCoApi.Models.Category", b =>
                {
                    b.HasOne("ShopCoApi.Models.Category", "ParentCategory")
                        .WithMany()
                        .HasForeignKey("ParentCategoryId");

                    b.Navigation("ParentCategory");
                });

            modelBuilder.Entity("ShopCoApi.Models.Product", b =>
                {
                    b.HasOne("ShopCoApi.Models.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("ShopCoApi.Models.ProductFaq", b =>
                {
                    b.HasOne("ShopCoApi.Models.Product", "Product")
                        .WithMany("Faqs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopCoApi.Models.ProductImage", b =>
                {
                    b.HasOne("ShopCoApi.Models.Product", "Product")
                        .WithMany("Images")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopCoApi.Models.ProductVariant", b =>
                {
                    b.HasOne("ShopCoApi.Models.Color", "Color")
                        .WithMany()
                        .HasForeignKey("ColorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopCoApi.Models.Product", "Product")
                        .WithMany("Variants")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopCoApi.Models.Size", "Size")
                        .WithMany()
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Color");

                    b.Navigation("Product");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("ShopCoApi.Models.Review", b =>
                {
                    b.HasOne("ShopCoApi.Models.Product", "Product")
                        .WithMany("Reviews")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });

            modelBuilder.Entity("ShopCoApi.Models.ShoppingCart", b =>
                {
                    b.HasOne("ShopCoApi.Models.ApplicationUser", "User")
                        .WithOne("ShoppingCart")
                        .HasForeignKey("ShopCoApi.Models.ShoppingCart", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("ShopCoApi.Models.ApplicationUser", b =>
                {
                    b.Navigation("ShoppingCart");
                });

            modelBuilder.Entity("ShopCoApi.Models.Category", b =>
                {
                    b.Navigation("Products");
                });

            modelBuilder.Entity("ShopCoApi.Models.Product", b =>
                {
                    b.Navigation("Faqs");

                    b.Navigation("Images");

                    b.Navigation("Reviews");

                    b.Navigation("Variants");
                });

            modelBuilder.Entity("ShopCoApi.Models.ShoppingCart", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
